rkam808/ConnecTrainer

app/controllers/bookings_controller.rb
app/controllers/dashboard_controller.rb
app/controllers/users_controller.rb
app/controllers/workouts_controller.rb
db/seeds.rb
test/controllers/bookings_controller_test.rb
test/controllers/dashboard_controller_test.rb
test/controllers/users_controller_test.rb
test/controllers/workouts_controller_test.rb

created controllers

---

Gemfile.lock
app/assets/stylesheets/components/_navbar.scss
app/javascript/components/navbar.js
app/javascript/packs/application.js
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb

added navbar

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/workouts_controller.rb
app/models/user.rb
app/policies/application_policy.rb
app/policies/workout_policy.rb
app/views/workouts/index.html.erb
app/views/workouts/new.html.erb
config/routes.rb
test/policies/workout_policy_test.rb

I added Pundit to our app for the workouts controller and also generated workout index and new view.

create pundit and workout view

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_navbar.scss
app/javascript/packs/application.js
app/views/shared/_navbar.html.erb
app/views/workouts/index.html.erb

fized navbar

---

app/controllers/workouts_controller.rb

fixed workout index policy issue

fixed index policy issue

---

app/assets/stylesheets/components/_banner.scss

fixed banner in wourkouts index

fixed banner in wourkouts index

---

db/migrate/20210525091555_add_description_to_workout.rb
db/migrate/20210525093600_add_price_to_workout.rb
db/schema.rb
db/seeds.rb

Added price and description text field to workout model 
Remember to migrate!

added price and description to workout

---

app/assets/stylesheets/application.scss
app/views/pages/home.html.erb
app/views/workouts/index.html.erb
app/views/workouts/show.html.erb

added navbar-fix class to top elements in views & erased mt-5

added navbar-fix class to top elements in views

---

app/controllers/bookings_controller.rb
app/controllers/workouts_controller.rb
app/policies/application_policy.rb
app/policies/booking_policy.rb
app/policies/workout_policy.rb
app/views/workouts/show.html.erb

Create Bookings from show page completed & additional touch ups to show page form/description

Trying to fix booking policy

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_search.scss
app/views/pages/home.html.erb

fixed background

---

.gitignore
Gemfile
Gemfile.lock
app/models/workout.rb
config/initializers/geocoder.rb
db/migrate/20210526024149_add_coordinates_to_workouts.rb
db/schema.rb

added geocoder and dotenv-rails gems

added geocoder and dotenv-rails gems

---

.gitignore
Gemfile
Gemfile.lock
app/models/user.rb
app/models/workout.rb
app/views/workouts/show.html.erb
config/environments/development.rb
config/environments/production.rb
config/storage.yml
db/migrate/20210526025058_create_active_storage_tables.active_storage.rb
db/schema.rb

Added cloudinary and changed background img of workout show page

Adding cloudinary

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_maps.scss
app/controllers/workouts_controller.rb
app/javascript/packs/application.js
app/javascript/plugins/init_mapbox.js
app/views/layouts/application.html.erb
app/views/workouts/_index-card.html.erb
app/views/workouts/index.html.erb
package.json
yarn.lock

changed styling and structure for workouts index page with maps

changed styling and structure for workouts index page with maps

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb
db/schema.rb

added logo

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_search.scss
app/views/pages/home.html.erb
app/views/shared/_search.html.erb
db/schema.rb

Fixed issue w/ search category and added roboto font

fixed issues with search category function

---

app/views/shared/_navbar.html.erb

changed navbar logo link path to root

changed navbar logo link path to root

---

app/assets/stylesheets/components/_show.scss
app/views/workouts/show.html.erb

fixed the box of create booking form

fixed showpage

---

app/assets/stylesheets/components/_search.scss
app/javascript/plugins/init_mapbox.js
app/views/workouts/_index-card.html.erb
app/views/workouts/index.html.erb

changed styling and added seach in workouts index

changed styling and added seach in workouts index

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_cards.scss
app/models/workout.rb
app/views/shared/_navbar.html.erb
app/views/workouts/_index-card.html.erb
app/views/workouts/show.html.erb
db/schema.rb
db/seeds.rb

Fixed seeds and added price to index cards

fixed seeds and made style corrections

---

app/assets/stylesheets/application.scss

changed hight in nav-fix class

changed hight in nav-fix class

---

app/views/workouts/_index-card.html.erb

changed card photo size in url

changed card photo size

---

app/views/shared/_navbar.html.erb

changed photo

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_maps.scss
app/controllers/workouts_controller.rb
app/javascript/plugins/init_mapbox.js
app/views/workouts/_index-card.html.erb
app/views/workouts/_info_window.html.erb

Added info window on the map and linked it to the show page.
I also changed markers' color to out theme color!

added info window on the map and linked it to the show page, changed markers color

---

Gemfile
Gemfile.lock
app/controllers/workouts_controller.rb
app/models/workout.rb
db/schema.rb

made search function work for any input (category or location)

completed search function

---

app/assets/stylesheets/components/_search.scss
app/views/shared/_search.html.erb
app/views/workouts/index.html.erb
app/views/workouts/show.html.erb
db/schema.rb

better styling

---

app/assets/stylesheets/components/_avatar.scss
app/views/shared/_navbar.html.erb

fixed avatar border

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_home.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

cleaned up some styling, mostly navbar styling and fonts

cleaned up navbar styling and fonts

---

app/views/shared/_navbar.html.erb

changed avatar photo to person's face because it kinda looked like we have two logos in navbar

changed avatar photo

---

app/assets/stylesheets/components/_sidebar.scss
app/assets/stylesheets/pages/_dashboard.scss
app/views/shared/_sidebar.html.erb

fixed dashboard styling

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_search.scss
app/controllers/workouts_controller.rb
app/views/pages/home.html.erb
app/views/shared/_search.html.erb

fixed search bar

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_navbar.scss
app/views/workouts/_index-card.html.erb
app/views/workouts/show.html.erb

better card styling

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_fonts.scss
app/views/workouts/_index-card.html.erb
app/views/workouts/show.html.erb

changed header fonts to roboto (for now, will reconsider tomorrow after consulting with team)

changed header fonts to roboto

---

app/views/shared/_map.html.erb
app/views/workouts/index.html.erb
app/views/workouts/show.html.erb

I fixed a map styling problem with a styling variable passed to the rendered element

map styling with variable problem fixed

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_sidebar.scss
app/views/shared/_map.html.erb
app/views/workouts/index.html.erb
app/views/workouts/show.html.erb

fixed 100vh height of home page banner and dashboard sidebar with calc

Hight fixed

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_search.scss
app/assets/stylesheets/components/_sidebar.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb
app/views/shared/_search.html.erb
app/views/shared/_sidebar.html.erb
app/views/workouts/_index-card.html.erb
app/views/workouts/new.html.erb

minor styling changes

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/views/pages/home.html.erb
app/views/shared/_footer.html.erb
app/views/workouts/index.html.erb
app/views/workouts/show.html.erb
db/schema.rb

added a footer

---

app/assets/stylesheets/components/_sidebar.scss
app/assets/stylesheets/workouts.scss
app/views/workouts/index.html.erb

added position sticky on dashboard sidebar and workouts index search and map

added position sticky

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_cards.scss
app/views/workouts/_index-card.html.erb
app/views/workouts/index.html.erb

added better link from workout index card to show page

---

app/assets/stylesheets/components/_cards.scss
app/views/workouts/_index-card.html.erb

deleted old link from index cards and it's styling

deleted old link

---

app/views/workouts/show.html.erb

capitalized

---

app/views/workouts/show.html.erb

fixed search button styling

---

app/controllers/dashboard_controller.rb
app/views/dashboard/index.html.erb

Confirmed requests are not removed from the pending table in the dashboard
if no pending requests the table is removed.

removed confirmed requests from pending table

---

app/views/workouts/_index-card.html.erb
app/views/workouts/show.html.erb

fixed styling and search form content on show page

fixed styling and search form content on show page

---

app/assets/stylesheets/components/_footer.scss
app/views/dashboard/index.html.erb
app/views/shared/_footer.html.erb

fixed footer style in general and position on dashboard

fixed footer 

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_search.scss
app/assets/stylesheets/workouts.scss
app/views/workouts/index.html.erb

made changes to the search bar NOT THE FOOTER

made changes to search bar in landing/index page

---

render.yaml

add value to yaml file
